name: a2pa
channels: [pytorch, nvidia, conda-forge]
dependencies:
  - python=3.10
  - pytorch
  - torchvision
  - pytorch-cuda=12.1  # remove if CPU-only
  - numpy
  - scipy
  - scikit-learn
  - xgboost
  - joblib
  - h5py
  - pandas
  - pillow
  - matplotlib
